apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: new
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: my-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
